/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.43
 * Generated at: 2025-08-08 06:52:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("	<head>\n");
      out.write("		<meta charset=\"UTF-8\">\n");
      out.write("		<title>index</title>\n");
      out.write("		<!-- \n");
      out.write("			날짜 : 2025/08/01\n");
      out.write("			이름 : 김철학\n");
      out.write("			내용 : 프로젝트 로그와 배포 실습하기			\n");
      out.write("			\n");
      out.write("			로그\n");
      out.write("			 - 시스템의 실행과정 및 서비스 개선을 위한 작업\n");
      out.write("			 - 로그 단계별 기록을 통해 서비스 개선\n");
      out.write("			 \n");
      out.write("			라이브러리(Maven 다운로드)\n");
      out.write("			 - logback-classic-1.5.18.jar\n");
      out.write("			 - logback-core-1.5.18.jar\n");
      out.write("			 - slf4j-api-2.0.17.jar\n");
      out.write("			\n");
      out.write("			로그 설정\n");
      out.write("			 - WEB-INF > classes 폴더 생성 > logback.xml 파일생성\n");
      out.write("			 - https://logback.qos.ch/manual/configuration.html 에서 설정 XML 복사\n");
      out.write("			\n");
      out.write("			배포\n");
      out.write("			 - 이클립스 프로젝트 > export > war 생성\n");
      out.write("			 - C:\\Users\\GGG\\apache-tomcat-10.1.43\\bin\\startup.bat 실행\n");
      out.write("			 - C:\\Users\\GGG\\apache-tomcat-10.1.43\\webapps 폴더에 배포파일(ch10.war) 업로드 후 Deploy 확인 후 브라우저 확인\n");
      out.write("		-->		\n");
      out.write("	</head>\n");
      out.write("	<body>\n");
      out.write("		<h3>프로젝트 로그와 배포</h3>\n");
      out.write("		\n");
      out.write("		<h4>Shop</h4>\n");
      out.write("		<a href=\"/ch10/shop/customer/list.do\">Customer CRUD</a>\n");
      out.write("		<a href=\"/ch10/shop/product/list.do\">Product CRUD</a>\n");
      out.write("		\n");
      out.write("		<h4>College</h4>\n");
      out.write("		<a href=\"/ch10/college/student/list.do\">Student CRUD</a>\n");
      out.write("		<a href=\"/ch10/college/course/list.do\">Course CRUD</a>\n");
      out.write("		\n");
      out.write("		<h4>Bank</h4>\n");
      out.write("		<a href=\"/ch10/bank/account/list.do\">Account CRUD</a>\n");
      out.write("		<a href=\"/ch10/bank/customer/list.do\">Customer CRUD</a>\n");
      out.write("		\n");
      out.write("		<h4>Library</h4>\n");
      out.write("		<a href=\"/ch10/library/member/list.do\">Member CRUD</a>\n");
      out.write("		<a href=\"/ch10/library/book/list.do\">Book CRUD</a>\n");
      out.write("		\n");
      out.write("		<h4>User1</h4>\n");
      out.write("		<a href=\"/ch10/user1/list.do\">user1 CRUD</a>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("	</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
